execute:
  execute_notebooks: "on"
  cache_on_build: "true"  # Caches notebook outputs during the build process
  cache_directory: ".cache"  # Directory for storing cached notebook outputs

# execute:
#  execute_notebooks: auto

sphinx:
 config:
   nb_execution_mode: auto
